  export const countries = [ "India", "US","UK", "Canada","Germany","UAE","Others"];
  export const experiences = [
    "0 - less than 1",
    "1 - less than 2",
    "2 - less than 4",
    "4 - less than 7",
    "7 - less than 10",
    "10 - less than 15",
    "15 plus"
  ];
  export const jobRoles = [  '.Net Developer',
    'AI/ML Solution Specialist',
    'Account Executive',
    'Account Manager',
    'Accountant',
    'Android Developer',
    'Application Developer',
    'Associate Product Manager',
    'Automation Engineer',
    'Backend Developer',
    'Business Analyst',
    'Business Consultant',
    'Business Development Executive',
    'Business Development Manager',
    'Business Intelligence',
    'C Developer',
    'C++ Developer',
    'Cloud Computing',
    'Cloud Engineer',
    'Company Secretary',
    'Compliance Executive / Officer',
    'Content Marketer',
    'Content Writer',
    'Credit Analyst',
    'Customer Success Manager',
    'Data Analyst',
    'Data Engineer',
    'Data Scientist',
    'Database Administrator',
    'Database Developer',
    'DevOps Engineer',
    'Digital Marketing Executive',
    'Digital Marketing Manager',
    'Embedded Software Engineer',
    'Finance Executive',
    'Finance Manager',
    'Finance Officer',
    'Financial Advisor',
    'Financial Analyst',
    'Frontend Developer',
    'Full Stack Developer',
    'Human Resources Executive',
    'Human Resources Manager',
    'Information Technology Analyst',
    'Information Technology Consultant',
    'Information Technology Manager',
    'Investment Analyst',
    'Java Developer',
    'Legal Associate / Counsel',
    'Logistics Coordinator',
    'Machine Learning Engineer',
    'Marketing Analyst',
    'Operations Executive',
    'Operations Manager',
    'PHP Developer',
    'Paralegal',
    'Process Associate',
    'Process Engineer',
    'Process Executive',
    'Product Analyst',
    'Product Manager',
    'Product Owner',
    'Program Manager',
    'Programming Analyst',
    'Project Coordinator',
    'Project Manager',
    'Python Developer',
    'Quality Analyst',
    'Quality Assurance Analyst',
    'Quality Assurance Manager',
    'Quality Engineer',
    'Recruitment Specialist',
    'SAP Consultant',
    'SEO Executive / Specialist',
    'Sales Executive',
    'Sales Manager',
    'Sales Officer',
    'Scrum Master',
    'Search Engine Optimization Analyst',
    'Search Engine Optimization Executive',
    'Senior Advocate',
    'Senior Legal Associate / Counsel',
    'Social Media Executive',
    'Social Media Manager',
    'Social Media Marketing',
    'Software Developer',
    'Software Quality Assurance Engineer',
    'Software Test Engineer',
    'Supply Chain Analyst',
    'Supply Chain Manager',
    'System Administrator',
    'System Analyst',
    'System Engineer',
    'Talent Acquisition Manager',
    'Technical Consultant',
    'Technical Support Engineer',
    'Test Analyst',
    'Test Engineer',
    'Test Specialist',
    'User Interface Designer',
    'Web Developer',
    'Wordpress',
  ];
